---
name: Build and Lint
on:
  - push
  - pull_request
jobs:
  build:
    uses: jabrown93/.github/.github/workflows/node-build.yml@0393d3de51e508488e6bc5e1101bf509e6359c14 # v1.5.1
    with:
      node-versions: '["22.x", "24.x"]'
