---
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    uses: jabrown93/.github/.github/workflows/stale.yml@0393d3de51e508488e6bc5e1101bf509e6359c14 # v1.5.1
    permissions:
      actions: write
      issues: write
      pull-requests: write
